CREATE TABLE Musteri (
id INT PRIMARY KEY IDENTITY (1,1), 
ad VARCHAR(50) NOT NULL,
soyad VARCHAR(50) NOT NULL,
email VARCHAR(100) UNIQUE, 
sehir VARCHAR(50),
kayit_tarihi DATETIME DEFAULT GETDATE()
);


CREATE TABLE Kategori (
id INT PRIMARY KEY IDENTITY (1,1), 
ad VARCHAR(500) NOT NULL,
);

CREATE TABLE Satici (
id INT PRIMARY KEY IDENTITY (1,1), 
ad VARCHAR(100) NOT NULL,
adres VARCHAR(250)
);

CREATE TABLE Siparis (
id INT PRIMARY KEY IDENTITY (1,1),
musteri_id INT FOREIGN KEY REFERENCES Musteri(id),
tarih  DATETIME DEFAULT GETDATE(),
toplam_tutar  DECIMAL(10,2),
odeme_turu NVARCHAR(50)
);

CREATE TABLE Urun (
id INT PRIMARY KEY IDENTITY (1,1), 
ad VARCHAR(50) NOT NULL,
fiyat DECIMAL(10,2) NOT NULL,
stok INT NOT NULL, 
kategori_id INT FOREIGN KEY REFERENCES Kategori(id) ,
satici_id INT FOREIGN KEY REFERENCES Satici(id)
);

CREATE TABLE Siparis_Detay (
id INT PRIMARY KEY IDENTITY (1,1),
siparis_id INT FOREIGN KEY REFERENCES Siparis(id),
urun_id INT FOREIGN KEY REFERENCES Urun(id), 
adet INT NOT NULL, 
fiyat DECIMAL(10,2) NOT NULL
);